// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAylJeVL8sHXvIMT-CVeOkGUVilu99LWos',
    appId: '1:858728453185:web:7a7da4efe7d7a9ad7aa2c0',
    messagingSenderId: '858728453185',
    projectId: 'fit-lovers-f0228',
    authDomain: 'fit-lovers-f0228.firebaseapp.com',
    storageBucket: 'fit-lovers-f0228.firebasestorage.app',
    measurementId: 'G-Y842JBTBRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUT97QzrQfszKeM9Id_ruA-Loa2e6d24E',
    appId: '1:858728453185:android:8b4b1e28a2e412a07aa2c0',
    messagingSenderId: '858728453185',
    projectId: 'fit-lovers-f0228',
    storageBucket: 'fit-lovers-f0228.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBELlP8sQkA7fk-xfFbiACdj5doCTcleQQ',
    appId: '1:858728453185:ios:8e5b2f237823612c7aa2c0',
    messagingSenderId: '858728453185',
    projectId: 'fit-lovers-f0228',
    storageBucket: 'fit-lovers-f0228.firebasestorage.app',
    iosBundleId: 'com.example.fitLovers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBELlP8sQkA7fk-xfFbiACdj5doCTcleQQ',
    appId: '1:858728453185:ios:8e5b2f237823612c7aa2c0',
    messagingSenderId: '858728453185',
    projectId: 'fit-lovers-f0228',
    storageBucket: 'fit-lovers-f0228.firebasestorage.app',
    iosBundleId: 'com.example.fitLovers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAylJeVL8sHXvIMT-CVeOkGUVilu99LWos',
    appId: '1:858728453185:web:a22e3caba8ef5dfb7aa2c0',
    messagingSenderId: '858728453185',
    projectId: 'fit-lovers-f0228',
    authDomain: 'fit-lovers-f0228.firebaseapp.com',
    storageBucket: 'fit-lovers-f0228.firebasestorage.app',
    measurementId: 'G-F7KT8QWQ3C',
  );
}
